const GET_MUEBLES = "GET_MUEBLES";
const GET_DETAIL = "GET_DETAIL";
const POST_MUEBLES = "POST_MUEBLES";
const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE";
const GET_MUEBLE_NAME = "GET_MUEBLE_NAME";


module.exports = {
  GET_MUEBLES,
  GET_DETAIL,
  POST_MUEBLES,
  GET_PRODUCT_TYPE,
  GET_MUEBLE_NAME,
};
