const GET_PRODUCTS = "GET_PRODUCTS";
const GET_DETAIL = "GET_DETAIL";
const SET_IMAGE_URL = "SET_IMAGE_URL";
const POST_PRODUCT = "POST_PRODUCT";
const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE";
const GET_COLOR = "GET_COLOR";
const GET_MATERIAL = "GET_MATERIAL";
const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
const SET_SORT = "SET_SORT";
const SET_PRODUCT_TYPE = "SET_PRODUCT_TYPE";
const SET_COLOR = "SET_COLOR";
const SET_PRICE_RANGE = "SET_PRICE_RANGE";
const SET_PRODUCTS_COPY = "SET_PRODUCTS_COPY";
const POST_CART_PRODUCT = "POST_CART_PRODUCT";
const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
const POST_USER = "POST_USER";
const GET_USER = "GET_USER";
const LOAD_CART_FROM_LOCAL_STORAGE = "LOAD_CART_FROM_LOCAL_STORAGE";
const POST_CART = "POST_CART";

module.exports = {
  GET_PRODUCTS,
  GET_DETAIL,
  SET_IMAGE_URL,
  POST_PRODUCT,
  GET_PRODUCT_TYPE,
  GET_COLOR,
  GET_MATERIAL,
  GET_PRODUCT_BY_NAME,
  SET_SORT,
  SET_PRODUCT_TYPE,
  SET_PRODUCTS_COPY,
  SET_COLOR,
  SET_PRICE_RANGE,
  POST_CART_PRODUCT,
  DELETE_CART_PRODUCT,
  POST_USER,
  GET_USER,
  LOAD_CART_FROM_LOCAL_STORAGE,
  POST_CART,
};
